export enum ActionType {
    TERM = 'setTerm',
    WORK = 'setWorks',
    SEARCH = 'setSearch',
    DATA = 'setArtworkData',
    LOADING = 'setIsLoading',
    ALL = 'setAllWorks',
    ISFAVORITES = 'setIsFavorites',
    PAGE = 'setCurrentPage',
    WINDOW = 'setWindowWidth',
    PERPAGE = 'setItemsPerPage',
    ARTWORK = 'setArtwork',
    FAVORITES = 'setFavorites',
    DELETE_FAVORITE = 'deleteFavorite',
    PAGINATION = 'setPagination',
}